version: "3.6"
services:
  traefik:
    image: traefik:v1.7
    command:
      - --debug=false
      - --logLevel=INFO
      - --defaultentrypoints=https,http
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --retry
      - --docker
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.swarmmode
      - --docker.domain=${HOST_NAME}
      - --docker.watch=true
      - --docker.exposedbydefault=false
#      - --acme.email=$WEB_MASTER_EMAIL
      - --acme.storage=/acme/acme.json
      - --acme.entryPoint=https
      - --acme.onHostRule=true
      - --acme.httpchallenge.entrypoint=http
      - --acme.acmelogging=true
      - --api
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/acme/
    networks:
      - proxy
    env_file:
      - .env
    deploy:
      labels:
        - "traefik.frontend.rule=Host:traefik.${HOST_NAME}"
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.docker.network=proxy"
        - "traefik.redirectorservice.frontend.entryPoints=http"
        - "traefik.redirectorservice.frontend.redirect.entryPoint=https"
        - "traefik.webservice.frontend.entryPoints=https"
        - "traefik.frontend.auth.basic.users=${TRAEFIK_USER}:${HASHED_PASSWORD}"

networks:
  proxy:
    external: true

volumes:
  acme:
